fragment sitemapPagesFields on Query {
  pageBlogPostCollection(
    order: [publishedDate_DESC]
    limit: 100
    locale: $locale
  ) {
    total
    items {
      slug
      internalName
      title
      sys {
        publishedAt
      }
    }
  }
  pageLandingCollection(order: [internalName_ASC], limit: 50, locale: $locale) {
    total
    items {
      slug
      internalName
      sys {
        publishedAt
      }
    }
  }
  pagesCollection(limit: 10, locale: $locale) {
    total
    items {
      slug
      sys {
        publishedAt
      }
    }
  }
  tagPageCollection(order: [tag_ASC], limit: 50, locale: $locale) {
    total
    items {
      tag
      internalName
      sys {
        publishedAt
      }
    }
  }
}

query sitemapPages($locale: String!) {
  ...sitemapPagesFields
}
